/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetArticle } from '../models';
import { AdminResultMetArticle } from '../models';
/**
 * MetArticleApi - axios parameter creator
 * @export
 */
export const MetArticleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 根据分组code获取文章
         * @param {string} groupCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetArticleGetMetArticleToCodeGroupCodePost: async (groupCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupCode' is not null or undefined
            if (groupCode === null || groupCode === undefined) {
                throw new RequiredError('groupCode','Required parameter groupCode was null or undefined when calling apiMetArticleGetMetArticleToCodeGroupCodePost.');
            }
            const localVarPath = `/api/metArticle/getMetArticleToCode/{groupCode}`
                .replace(`{${"groupCode"}}`, encodeURIComponent(String(groupCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据Id获取文章
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetArticleGetMetArticleToIdIdPost: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiMetArticleGetMetArticleToIdIdPost.');
            }
            const localVarPath = `/api/metArticle/getMetArticleToId/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetArticleApi - functional programming interface
 * @export
 */
export const MetArticleApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 根据分组code获取文章
         * @param {string} groupCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetArticle>>> {
            const localVarAxiosArgs = await MetArticleApiAxiosParamCreator(configuration).apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 根据Id获取文章
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetArticleGetMetArticleToIdIdPost(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultMetArticle>>> {
            const localVarAxiosArgs = await MetArticleApiAxiosParamCreator(configuration).apiMetArticleGetMetArticleToIdIdPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetArticleApi - factory interface
 * @export
 */
export const MetArticleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 根据分组code获取文章
         * @param {string} groupCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetArticle>> {
            return MetArticleApiFp(configuration).apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据Id获取文章
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetArticleGetMetArticleToIdIdPost(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultMetArticle>> {
            return MetArticleApiFp(configuration).apiMetArticleGetMetArticleToIdIdPost(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetArticleApi - object-oriented interface
 * @export
 * @class MetArticleApi
 * @extends {BaseAPI}
 */
export class MetArticleApi extends BaseAPI {
    /**
     * 
     * @summary 根据分组code获取文章
     * @param {string} groupCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetArticleApi
     */
    public async apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetArticle>> {
        return MetArticleApiFp(this.configuration).apiMetArticleGetMetArticleToCodeGroupCodePost(groupCode, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 根据Id获取文章
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetArticleApi
     */
    public async apiMetArticleGetMetArticleToIdIdPost(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultMetArticle>> {
        return MetArticleApiFp(this.configuration).apiMetArticleGetMetArticleToIdIdPost(id, options).then((request) => request(this.axios, this.basePath));
    }
}
