/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultBoolean } from '../models';
import { AdminResultRankOutput } from '../models';
import { AdminResultSysUser } from '../models';
import { AdminResultUserQrcodeOutput } from '../models';
import { MetUserUpdatePhoneInput } from '../models';
import { RunkListInput } from '../models';
/**
 * MetUserApi - axios parameter creator
 * @export
 */
export const MetUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取我的微信公众号二维码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetUserGetPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metUser/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取邀请积分排行榜
         * @param {RunkListInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetUserRanklistPost: async (body?: RunkListInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metUser/ranklist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 转发文章积分
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetUserStaffSharePost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metUser/staffShare`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取员工信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetUserStaffUserInfoPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metUser/staffUserInfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 修改绑定的手机号
         * @param {MetUserUpdatePhoneInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetUserUpdatePhonePost: async (body?: MetUserUpdatePhoneInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metUser/updatePhone`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetUserApi - functional programming interface
 * @export
 */
export const MetUserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取我的微信公众号二维码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserGetPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultUserQrcodeOutput>>> {
            const localVarAxiosArgs = await MetUserApiAxiosParamCreator(configuration).apiMetUserGetPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取邀请积分排行榜
         * @param {RunkListInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserRanklistPost(body?: RunkListInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultRankOutput>>> {
            const localVarAxiosArgs = await MetUserApiAxiosParamCreator(configuration).apiMetUserRanklistPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 转发文章积分
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserStaffSharePost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await MetUserApiAxiosParamCreator(configuration).apiMetUserStaffSharePost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取员工信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserStaffUserInfoPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultSysUser>>> {
            const localVarAxiosArgs = await MetUserApiAxiosParamCreator(configuration).apiMetUserStaffUserInfoPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 修改绑定的手机号
         * @param {MetUserUpdatePhoneInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserUpdatePhonePost(body?: MetUserUpdatePhoneInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultBoolean>>> {
            const localVarAxiosArgs = await MetUserApiAxiosParamCreator(configuration).apiMetUserUpdatePhonePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetUserApi - factory interface
 * @export
 */
export const MetUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取我的微信公众号二维码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserGetPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultUserQrcodeOutput>> {
            return MetUserApiFp(configuration).apiMetUserGetPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取邀请积分排行榜
         * @param {RunkListInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserRanklistPost(body?: RunkListInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultRankOutput>> {
            return MetUserApiFp(configuration).apiMetUserRanklistPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 转发文章积分
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserStaffSharePost(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return MetUserApiFp(configuration).apiMetUserStaffSharePost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取员工信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserStaffUserInfoPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultSysUser>> {
            return MetUserApiFp(configuration).apiMetUserStaffUserInfoPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 修改绑定的手机号
         * @param {MetUserUpdatePhoneInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetUserUpdatePhonePost(body?: MetUserUpdatePhoneInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultBoolean>> {
            return MetUserApiFp(configuration).apiMetUserUpdatePhonePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetUserApi - object-oriented interface
 * @export
 * @class MetUserApi
 * @extends {BaseAPI}
 */
export class MetUserApi extends BaseAPI {
    /**
     * 
     * @summary 获取我的微信公众号二维码
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetUserApi
     */
    public async apiMetUserGetPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultUserQrcodeOutput>> {
        return MetUserApiFp(this.configuration).apiMetUserGetPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取邀请积分排行榜
     * @param {RunkListInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetUserApi
     */
    public async apiMetUserRanklistPost(body?: RunkListInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultRankOutput>> {
        return MetUserApiFp(this.configuration).apiMetUserRanklistPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 转发文章积分
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetUserApi
     */
    public async apiMetUserStaffSharePost(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return MetUserApiFp(this.configuration).apiMetUserStaffSharePost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取员工信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetUserApi
     */
    public async apiMetUserStaffUserInfoPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultSysUser>> {
        return MetUserApiFp(this.configuration).apiMetUserStaffUserInfoPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 修改绑定的手机号
     * @param {MetUserUpdatePhoneInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetUserApi
     */
    public async apiMetUserUpdatePhonePost(body?: MetUserUpdatePhoneInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultBoolean>> {
        return MetUserApiFp(this.configuration).apiMetUserUpdatePhonePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
