/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetBanner } from '../models';
import { MetBannerEnum } from '../models';
/**
 * MetBannerApi - axios parameter creator
 * @export
 */
export const MetBannerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取banner图片
         * @param {MetBannerEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetBannerGetTypeGet: async (type: MetBannerEnum, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            if (type === null || type === undefined) {
                throw new RequiredError('type','Required parameter type was null or undefined when calling apiMetBannerGetTypeGet.');
            }
            const localVarPath = `/api/metBanner/get/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetBannerApi - functional programming interface
 * @export
 */
export const MetBannerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取banner图片
         * @param {MetBannerEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetBannerGetTypeGet(type: MetBannerEnum, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetBanner>>> {
            const localVarAxiosArgs = await MetBannerApiAxiosParamCreator(configuration).apiMetBannerGetTypeGet(type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetBannerApi - factory interface
 * @export
 */
export const MetBannerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取banner图片
         * @param {MetBannerEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetBannerGetTypeGet(type: MetBannerEnum, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetBanner>> {
            return MetBannerApiFp(configuration).apiMetBannerGetTypeGet(type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetBannerApi - object-oriented interface
 * @export
 * @class MetBannerApi
 * @extends {BaseAPI}
 */
export class MetBannerApi extends BaseAPI {
    /**
     * 
     * @summary 获取banner图片
     * @param {MetBannerEnum} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetBannerApi
     */
    public async apiMetBannerGetTypeGet(type: MetBannerEnum, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetBanner>> {
        return MetBannerApiFp(this.configuration).apiMetBannerGetTypeGet(type, options).then((request) => request(this.axios, this.basePath));
    }
}
