/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultBoolean } from '../models';
import { AdminResultUserInfoOutput } from '../models';
/**
 * MetDoctorApi - axios parameter creator
 * @export
 */
export const MetDoctorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 记录阅读文章积分
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetDoctorArticleIntegralKeyPost: async (key: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            if (key === null || key === undefined) {
                throw new RequiredError('key','Required parameter key was null or undefined when calling apiMetDoctorArticleIntegralKeyPost.');
            }
            const localVarPath = `/api/metDoctor/articleIntegral/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据Id获取医生信息
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetDoctorGetDoctorToIdPost: async (id?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metDoctor/getDoctorToId`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据手机号获取医生信息
         * @param {string} [phone] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetDoctorGetDoctorToPhonePost: async (phone?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metDoctor/getDoctorToPhone`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            if (phone !== undefined) {
                localVarQueryParameter['phone'] = phone;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetDoctorApi - functional programming interface
 * @export
 */
export const MetDoctorApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 记录阅读文章积分
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorArticleIntegralKeyPost(key: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultBoolean>>> {
            const localVarAxiosArgs = await MetDoctorApiAxiosParamCreator(configuration).apiMetDoctorArticleIntegralKeyPost(key, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 根据Id获取医生信息
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorGetDoctorToIdPost(id?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultUserInfoOutput>>> {
            const localVarAxiosArgs = await MetDoctorApiAxiosParamCreator(configuration).apiMetDoctorGetDoctorToIdPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 根据手机号获取医生信息
         * @param {string} [phone] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorGetDoctorToPhonePost(phone?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultUserInfoOutput>>> {
            const localVarAxiosArgs = await MetDoctorApiAxiosParamCreator(configuration).apiMetDoctorGetDoctorToPhonePost(phone, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetDoctorApi - factory interface
 * @export
 */
export const MetDoctorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 记录阅读文章积分
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorArticleIntegralKeyPost(key: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultBoolean>> {
            return MetDoctorApiFp(configuration).apiMetDoctorArticleIntegralKeyPost(key, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据Id获取医生信息
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorGetDoctorToIdPost(id?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultUserInfoOutput>> {
            return MetDoctorApiFp(configuration).apiMetDoctorGetDoctorToIdPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据手机号获取医生信息
         * @param {string} [phone] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetDoctorGetDoctorToPhonePost(phone?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultUserInfoOutput>> {
            return MetDoctorApiFp(configuration).apiMetDoctorGetDoctorToPhonePost(phone, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetDoctorApi - object-oriented interface
 * @export
 * @class MetDoctorApi
 * @extends {BaseAPI}
 */
export class MetDoctorApi extends BaseAPI {
    /**
     * 
     * @summary 记录阅读文章积分
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetDoctorApi
     */
    public async apiMetDoctorArticleIntegralKeyPost(key: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultBoolean>> {
        return MetDoctorApiFp(this.configuration).apiMetDoctorArticleIntegralKeyPost(key, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 根据Id获取医生信息
     * @param {number} [id] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetDoctorApi
     */
    public async apiMetDoctorGetDoctorToIdPost(id?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultUserInfoOutput>> {
        return MetDoctorApiFp(this.configuration).apiMetDoctorGetDoctorToIdPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 根据手机号获取医生信息
     * @param {string} [phone] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetDoctorApi
     */
    public async apiMetDoctorGetDoctorToPhonePost(phone?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultUserInfoOutput>> {
        return MetDoctorApiFp(this.configuration).apiMetDoctorGetDoctorToPhonePost(phone, options).then((request) => request(this.axios, this.basePath));
    }
}
