/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetMeetingGift } from '../models';
import { GiftMetMeetingInput } from '../models';
/**
 * MetMeetingGiftApi - axios parameter creator
 * @export
 */
export const MetMeetingGiftApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取会议礼品清单
         * @param {number} meetingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetMeetingGiftGetMeetingIdGet: async (meetingId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meetingId' is not null or undefined
            if (meetingId === null || meetingId === undefined) {
                throw new RequiredError('meetingId','Required parameter meetingId was null or undefined when calling apiMetMeetingGiftGetMeetingIdGet.');
            }
            const localVarPath = `/api/metMeetingGift/get/{meetingId}`
                .replace(`{${"meetingId"}}`, encodeURIComponent(String(meetingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 授权会议礼品
         * @param {GiftMetMeetingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetMeetingGiftSetMeetGiftPost: async (body?: GiftMetMeetingInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metMeetingGift/setMeetGift`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetMeetingGiftApi - functional programming interface
 * @export
 */
export const MetMeetingGiftApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取会议礼品清单
         * @param {number} meetingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetMeetingGiftGetMeetingIdGet(meetingId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetMeetingGift>>> {
            const localVarAxiosArgs = await MetMeetingGiftApiAxiosParamCreator(configuration).apiMetMeetingGiftGetMeetingIdGet(meetingId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 授权会议礼品
         * @param {GiftMetMeetingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetMeetingGiftSetMeetGiftPost(body?: GiftMetMeetingInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await MetMeetingGiftApiAxiosParamCreator(configuration).apiMetMeetingGiftSetMeetGiftPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetMeetingGiftApi - factory interface
 * @export
 */
export const MetMeetingGiftApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取会议礼品清单
         * @param {number} meetingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetMeetingGiftGetMeetingIdGet(meetingId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetMeetingGift>> {
            return MetMeetingGiftApiFp(configuration).apiMetMeetingGiftGetMeetingIdGet(meetingId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 授权会议礼品
         * @param {GiftMetMeetingInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetMeetingGiftSetMeetGiftPost(body?: GiftMetMeetingInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return MetMeetingGiftApiFp(configuration).apiMetMeetingGiftSetMeetGiftPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetMeetingGiftApi - object-oriented interface
 * @export
 * @class MetMeetingGiftApi
 * @extends {BaseAPI}
 */
export class MetMeetingGiftApi extends BaseAPI {
    /**
     * 
     * @summary 获取会议礼品清单
     * @param {number} meetingId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetMeetingGiftApi
     */
    public async apiMetMeetingGiftGetMeetingIdGet(meetingId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetMeetingGift>> {
        return MetMeetingGiftApiFp(this.configuration).apiMetMeetingGiftGetMeetingIdGet(meetingId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 授权会议礼品
     * @param {GiftMetMeetingInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetMeetingGiftApi
     */
    public async apiMetMeetingGiftSetMeetGiftPost(body?: GiftMetMeetingInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return MetMeetingGiftApiFp(this.configuration).apiMetMeetingGiftSetMeetGiftPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
