/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetBigTalk } from '../models';
import { MetBigTalkInput } from '../models';
/**
 * MetBigTalkApi - axios parameter creator
 * @export
 */
export const MetBigTalkApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取大咖语录清单
         * @param {MetBigTalkInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetBigTalkListPost: async (body?: MetBigTalkInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metBigTalk/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetBigTalkApi - functional programming interface
 * @export
 */
export const MetBigTalkApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取大咖语录清单
         * @param {MetBigTalkInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetBigTalkListPost(body?: MetBigTalkInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetBigTalk>>> {
            const localVarAxiosArgs = await MetBigTalkApiAxiosParamCreator(configuration).apiMetBigTalkListPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetBigTalkApi - factory interface
 * @export
 */
export const MetBigTalkApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取大咖语录清单
         * @param {MetBigTalkInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetBigTalkListPost(body?: MetBigTalkInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetBigTalk>> {
            return MetBigTalkApiFp(configuration).apiMetBigTalkListPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetBigTalkApi - object-oriented interface
 * @export
 * @class MetBigTalkApi
 * @extends {BaseAPI}
 */
export class MetBigTalkApi extends BaseAPI {
    /**
     * 
     * @summary 获取大咖语录清单
     * @param {MetBigTalkInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetBigTalkApi
     */
    public async apiMetBigTalkListPost(body?: MetBigTalkInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetBigTalk>> {
        return MetBigTalkApiFp(this.configuration).apiMetBigTalkListPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
