/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetIntegralRecord } from '../models';
/**
 * MetStaffIntegralApi - axios parameter creator
 * @export
 */
export const MetStaffIntegralApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取我名下医生的积分记录根据时间排序
         * @param {number} doctorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetStaffIntegralListDoctorIdPost: async (doctorId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'doctorId' is not null or undefined
            if (doctorId === null || doctorId === undefined) {
                throw new RequiredError('doctorId','Required parameter doctorId was null or undefined when calling apiMetStaffIntegralListDoctorIdPost.');
            }
            const localVarPath = `/api/metStaffIntegral/list/{doctorId}`
                .replace(`{${"doctorId"}}`, encodeURIComponent(String(doctorId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetStaffIntegralApi - functional programming interface
 * @export
 */
export const MetStaffIntegralApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取我名下医生的积分记录根据时间排序
         * @param {number} doctorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetStaffIntegralListDoctorIdPost(doctorId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetIntegralRecord>>> {
            const localVarAxiosArgs = await MetStaffIntegralApiAxiosParamCreator(configuration).apiMetStaffIntegralListDoctorIdPost(doctorId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetStaffIntegralApi - factory interface
 * @export
 */
export const MetStaffIntegralApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取我名下医生的积分记录根据时间排序
         * @param {number} doctorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetStaffIntegralListDoctorIdPost(doctorId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetIntegralRecord>> {
            return MetStaffIntegralApiFp(configuration).apiMetStaffIntegralListDoctorIdPost(doctorId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetStaffIntegralApi - object-oriented interface
 * @export
 * @class MetStaffIntegralApi
 * @extends {BaseAPI}
 */
export class MetStaffIntegralApi extends BaseAPI {
    /**
     * 
     * @summary 获取我名下医生的积分记录根据时间排序
     * @param {number} doctorId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetStaffIntegralApi
     */
    public async apiMetStaffIntegralListDoctorIdPost(doctorId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetIntegralRecord>> {
        return MetStaffIntegralApiFp(this.configuration).apiMetStaffIntegralListDoctorIdPost(doctorId, options).then((request) => request(this.axios, this.basePath));
    }
}
