/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListMetStaffDoctor } from '../models';
/**
 * MetStaffDoctorApi - axios parameter creator
 * @export
 */
export const MetStaffDoctorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 查询员工名下所有的医生信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetStaffDoctorListPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/metStaffDoctor/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetStaffDoctorApi - functional programming interface
 * @export
 */
export const MetStaffDoctorApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 查询员工名下所有的医生信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetStaffDoctorListPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListMetStaffDoctor>>> {
            const localVarAxiosArgs = await MetStaffDoctorApiAxiosParamCreator(configuration).apiMetStaffDoctorListPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetStaffDoctorApi - factory interface
 * @export
 */
export const MetStaffDoctorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 查询员工名下所有的医生信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetStaffDoctorListPost(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListMetStaffDoctor>> {
            return MetStaffDoctorApiFp(configuration).apiMetStaffDoctorListPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetStaffDoctorApi - object-oriented interface
 * @export
 * @class MetStaffDoctorApi
 * @extends {BaseAPI}
 */
export class MetStaffDoctorApi extends BaseAPI {
    /**
     * 
     * @summary 查询员工名下所有的医生信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetStaffDoctorApi
     */
    public async apiMetStaffDoctorListPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListMetStaffDoctor>> {
        return MetStaffDoctorApiFp(this.configuration).apiMetStaffDoctorListPost(options).then((request) => request(this.axios, this.basePath));
    }
}
