/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultObject } from '../models';
/**
 * SysReportApi - axios parameter creator
 * @export
 */
export const SysReportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 周三大讲堂
         * @param {string} name 
         * @param {string} chrSearch0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysReportGetNameChrSearch0Post: async (name: string, chrSearch0: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling apiSysReportGetNameChrSearch0Post.');
            }
            // verify required parameter 'chrSearch0' is not null or undefined
            if (chrSearch0 === null || chrSearch0 === undefined) {
                throw new RequiredError('chrSearch0','Required parameter chrSearch0 was null or undefined when calling apiSysReportGetNameChrSearch0Post.');
            }
            const localVarPath = `/api/sysReport/get/{name}/{chrSearch0}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)))
                .replace(`{${"chrSearch0"}}`, encodeURIComponent(String(chrSearch0)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysReportApi - functional programming interface
 * @export
 */
export const SysReportApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 周三大讲堂
         * @param {string} name 
         * @param {string} chrSearch0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysReportGetNameChrSearch0Post(name: string, chrSearch0: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultObject>>> {
            const localVarAxiosArgs = await SysReportApiAxiosParamCreator(configuration).apiSysReportGetNameChrSearch0Post(name, chrSearch0, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysReportApi - factory interface
 * @export
 */
export const SysReportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 周三大讲堂
         * @param {string} name 
         * @param {string} chrSearch0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysReportGetNameChrSearch0Post(name: string, chrSearch0: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultObject>> {
            return SysReportApiFp(configuration).apiSysReportGetNameChrSearch0Post(name, chrSearch0, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysReportApi - object-oriented interface
 * @export
 * @class SysReportApi
 * @extends {BaseAPI}
 */
export class SysReportApi extends BaseAPI {
    /**
     * 
     * @summary 周三大讲堂
     * @param {string} name 
     * @param {string} chrSearch0 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysReportApi
     */
    public async apiSysReportGetNameChrSearch0Post(name: string, chrSearch0: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultObject>> {
        return SysReportApiFp(this.configuration).apiSysReportGetNameChrSearch0Post(name, chrSearch0, options).then((request) => request(this.axios, this.basePath));
    }
}
