/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 账号类型枚举<br />&nbsp;员工 Member = 666<br />&nbsp;普通账号 NormalUser = 777<br />&nbsp;系统管理员 SysAdmin = 888<br />&nbsp;超级管理员 SuperAdmin = 999<br />
 * @export
 * @enum {string}
 */
export enum AccountTypeEnum {
    NUMBER_666 = 666,
    NUMBER_777 = 777,
    NUMBER_888 = 888,
    NUMBER_999 = 999
}

