/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AnswerInfo
 */
export interface AnswerInfo {
    /**
     * 题目Id
     * @type {number}
     * @memberof AnswerInfo
     */
    topicId?: number;
    /**
     * 答案
     * @type {string}
     * @memberof AnswerInfo
     */
    answer?: string | null;
}
