/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 内容类型枚举<br />&nbsp;文本类型 TEXT = 1<br />&nbsp;视频类型 VIDEO = 2<br />&nbsp;图片类型 IMAGE = 3<br />&nbsp;语音类型 VOICE = 4<br />&nbsp;外链类型 LINK = 5<br />&nbsp;PDF文件 PDF = 6<br />
 * @export
 * @enum {string}
 */
export enum ContentTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}

