/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DescribeLiveStreamStateOutput
 */
export interface DescribeLiveStreamStateOutput {
    /**
     * 
     * @type {Error}
     * @memberof DescribeLiveStreamStateOutput
     */
    error?: Error;
    /**
     * 
     * @type {string}
     * @memberof DescribeLiveStreamStateOutput
     */
    requestId?: string | null;
    /**
     * active：活跃，  inactive：非活跃，  forbid：禁播。
     * @type {string}
     * @memberof DescribeLiveStreamStateOutput
     */
    streamState?: string | null;
}
