/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GiftMetMeetingInput
 */
export interface GiftMetMeetingInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof GiftMetMeetingInput
     */
    id: number;
    /**
     * 礼品Id集合
     * @type {Array<number>}
     * @memberof GiftMetMeetingInput
     */
    giftIdList?: Array<number> | null;
}
