/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 会议状态枚举<br />&nbsp;全部 All = 0<br />&nbsp;未开始 NotStarted = 1<br />&nbsp;进行中 InProgress = 2<br />&nbsp;已完成 Completed = 3<br />&nbsp;回放中 PlayBack = 4<br />
 * @export
 * @enum {string}
 */
export enum MeetingStateEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

