/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetGift } from './met-gift';
/**
 * 会议礼品表
 * @export
 * @interface MetMeetingGift
 */
export interface MetMeetingGift {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetMeetingGift
     */
    id?: number;
    /**
     * 会议ID
     * @type {number}
     * @memberof MetMeetingGift
     */
    meetingId?: number;
    /**
     * 礼品ID
     * @type {number}
     * @memberof MetMeetingGift
     */
    giftId?: number;
    /**
     * 
     * @type {MetGift}
     * @memberof MetMeetingGift
     */
    gift?: MetGift;
}
