/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeetingStateEnum } from './meeting-state-enum';
/**
 * 
 * @export
 * @interface MetMeetingInput
 */
export interface MetMeetingInput {
    /**
     * 名称
     * @type {string}
     * @memberof MetMeetingInput
     */
    name?: string | null;
    /**
     * 
     * @type {MeetingStateEnum}
     * @memberof MetMeetingInput
     */
    meetingState?: MeetingStateEnum;
    /**
     * 会议组别
     * @type {string}
     * @memberof MetMeetingInput
     */
    meetGroupCode?: string | null;
}
