/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentTypeEnum } from './content-type-enum';
import { MetProduct } from './met-product';
/**
 * 精彩时刻
 * @export
 * @interface MetMoments
 */
export interface MetMoments {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetMoments
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetMoments
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetMoments
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetMoments
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetMoments
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetMoments
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetMoments
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetMoments
     */
    isDelete?: boolean;
    /**
     * 描述 : 标题  空值 : True  默认 :
     * @type {string}
     * @memberof MetMoments
     */
    name?: string | null;
    /**
     * 描述 : 简介  空值 : True  默认 :
     * @type {string}
     * @memberof MetMoments
     */
    introduction?: string | null;
    /**
     * 描述 : 主形象  空值 : True  默认 :
     * @type {string}
     * @memberof MetMoments
     */
    mainImgUrl?: string | null;
    /**
     * 描述 : 内容  空值 : True  默认 :
     * @type {string}
     * @memberof MetMoments
     */
    contentText?: string | null;
    /**
     * 
     * @type {ContentTypeEnum}
     * @memberof MetMoments
     */
    type?: ContentTypeEnum;
    /**
     * 品牌ID
     * @type {number}
     * @memberof MetMoments
     */
    productId?: number | null;
    /**
     * 
     * @type {MetProduct}
     * @memberof MetMoments
     */
    product?: MetProduct;
    /**
     * 排序
     * @type {number}
     * @memberof MetMoments
     */
    orderNo?: number;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {number}
     * @memberof MetMoments
     */
    visits?: number;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetMoments
     */
    isSuggest?: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetMoments
     */
    isOnline?: boolean;
}
