/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetTagTypeEnum } from './met-tag-type-enum';
/**
 * 业务标签
 * @export
 * @interface MetTag
 */
export interface MetTag {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetTag
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetTag
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetTag
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetTag
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetTag
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetTag
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetTag
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetTag
     */
    isDelete?: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {string}
     * @memberof MetTag
     */
    name?: string | null;
    /**
     * 
     * @type {MetTagTypeEnum}
     * @memberof MetTag
     */
    type?: MetTagTypeEnum;
}
