/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetDoctor } from './met-doctor';
import { MetGift } from './met-gift';
import { MetIntegralGroupEnum } from './met-integral-group-enum';
import { MetIntegralRule } from './met-integral-rule';
import { MetIntegralTypeEnum } from './met-integral-type-enum';
import { SysUser } from './sys-user';
import { UserIdentityEnum } from './user-identity-enum';
/**
 * 积分记录
 * @export
 * @interface MetIntegralRecord
 */
export interface MetIntegralRecord {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetIntegralRecord
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetIntegralRecord
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetIntegralRecord
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetIntegralRecord
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetIntegralRecord
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetIntegralRecord
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetIntegralRecord
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetIntegralRecord
     */
    isDelete?: boolean;
    /**
     * 
     * @type {MetIntegralTypeEnum}
     * @memberof MetIntegralRecord
     */
    type?: MetIntegralTypeEnum;
    /**
     * 
     * @type {MetIntegralGroupEnum}
     * @memberof MetIntegralRecord
     */
    group?: MetIntegralGroupEnum;
    /**
     * 积分
     * @type {number}
     * @memberof MetIntegralRecord
     */
    integral?: number;
    /**
     * 记录类型为获取的时候有效
     * @type {number}
     * @memberof MetIntegralRecord
     */
    metIntegralId?: number;
    /**
     * 
     * @type {MetIntegralRule}
     * @memberof MetIntegralRecord
     */
    metIntegralRuleInfo?: MetIntegralRule;
    /**
     * 记录类型为消耗的时候有效
     * @type {number}
     * @memberof MetIntegralRecord
     */
    metGiftId?: number;
    /**
     * 
     * @type {MetGift}
     * @memberof MetIntegralRecord
     */
    metGiftInfo?: MetGift;
    /**
     * 用户ID-获取到积分的用户
     * @type {number}
     * @memberof MetIntegralRecord
     */
    userId?: number;
    /**
     * 
     * @type {UserIdentityEnum}
     * @memberof MetIntegralRecord
     */
    userIdentity?: UserIdentityEnum;
    /**
     * 
     * @type {SysUser}
     * @memberof MetIntegralRecord
     */
    staff?: SysUser;
    /**
     * 
     * @type {MetDoctor}
     * @memberof MetIntegralRecord
     */
    doctor?: MetDoctor;
    /**
     * 用户ID（赠送积分的用户）
     * @type {number}
     * @memberof MetIntegralRecord
     */
    giveUserId?: number;
    /**
     * 
     * @type {SysUser}
     * @memberof MetIntegralRecord
     */
    giveStaff?: SysUser;
    /**
     * 
     * @type {MetDoctor}
     * @memberof MetIntegralRecord
     */
    giveDoctor?: MetDoctor;
    /**
     * 事件ID
     * @type {string}
     * @memberof MetIntegralRecord
     */
    eventID?: string | null;
}
