/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetCaseTag } from './met-case-tag';
import { MetProduct } from './met-product';
/**
 * 互动病例详情表
 * @export
 * @interface MetCase
 */
export interface MetCase {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetCase
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetCase
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetCase
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetCase
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetCase
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetCase
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetCase
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetCase
     */
    isDelete?: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {string}
     * @memberof MetCase
     */
    name: string;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {string}
     * @memberof MetCase
     */
    mainImg: string;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {number}
     * @memberof MetCase
     */
    visits?: number;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {string}
     * @memberof MetCase
     */
    link?: string | null;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetCase
     */
    isUpload: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetCase
     */
    isOnline: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetCase
     */
    isSuggest: boolean;
    /**
     * 病例标签
     * @type {Array<MetCaseTag>}
     * @memberof MetCase
     */
    tags?: Array<MetCaseTag> | null;
    /**
     * 品牌ID
     * @type {number}
     * @memberof MetCase
     */
    productId: number;
    /**
     * 
     * @type {MetProduct}
     * @memberof MetCase
     */
    product?: MetProduct;
}
