/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 标签枚举<br />&nbsp;会议 Meet = 0<br />&nbsp;病例 Case = 1<br />
 * @export
 * @enum {string}
 */
export enum MetTagTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

