/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MetCaseInput
 */
export interface MetCaseInput {
    /**
     * 关键字查询
     * @type {string}
     * @memberof MetCaseInput
     */
    searchKey?: string | null;
    /**
     * 品牌ID
     * @type {number}
     * @memberof MetCaseInput
     */
    productId?: number | null;
}
