/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetDoctor } from './met-doctor';
import { UserIdentityEnum } from './user-identity-enum';
/**
 * 员工和医生绑定关系表
 * @export
 * @interface MetStaffDoctor
 */
export interface MetStaffDoctor {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetStaffDoctor
     */
    id?: number;
    /**
     * 员工ID
     * @type {number}
     * @memberof MetStaffDoctor
     */
    staffId?: number;
    /**
     * 被邀请医生ID
     * @type {number}
     * @memberof MetStaffDoctor
     */
    doctorId?: number;
    /**
     * 
     * @type {MetDoctor}
     * @memberof MetStaffDoctor
     */
    doctorInfo?: MetDoctor;
    /**
     * 邀请Id(包含员工和医生)是医生：说明是我名下的医生邀请的医生
     * @type {number}
     * @memberof MetStaffDoctor
     */
    inviteId?: number;
    /**
     * 
     * @type {UserIdentityEnum}
     * @memberof MetStaffDoctor
     */
    inviteIdentity?: UserIdentityEnum;
}
