/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserIdentityEnum } from './user-identity-enum';
/**
 * 
 * @export
 * @interface MetAuthBindingInput
 */
export interface MetAuthBindingInput {
    /**
     * 姓名
     * @type {string}
     * @memberof MetAuthBindingInput
     */
    name?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof MetAuthBindingInput
     */
    phone?: string | null;
    /**
     * 手机号码验证码
     * @type {string}
     * @memberof MetAuthBindingInput
     */
    smsCode?: string | null;
    /**
     * 描述 : 医院ID   空值 : True  默认 :
     * @type {number}
     * @memberof MetAuthBindingInput
     */
    hospitalId?: number;
    /**
     * 描述 : 职称   空值 : True  默认 :
     * @type {string}
     * @memberof MetAuthBindingInput
     */
    titles?: string | null;
    /**
     * 描述 : 科室   空值 : True  默认 :
     * @type {string}
     * @memberof MetAuthBindingInput
     */
    department?: string | null;
    /**
     * 
     * @type {UserIdentityEnum}
     * @memberof MetAuthBindingInput
     */
    bingUserType?: UserIdentityEnum;
    /**
     * 描述 : 员工ID，仅用户医生注册  空值 : True  默认 :
     * @type {number}
     * @memberof MetAuthBindingInput
     */
    staffId?: number;
}
