/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 积分规则
 * @export
 * @interface MetIntegralRule
 */
export interface MetIntegralRule {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetIntegralRule
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetIntegralRule
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetIntegralRule
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetIntegralRule
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetIntegralRule
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetIntegralRule
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetIntegralRule
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetIntegralRule
     */
    isDelete?: boolean;
    /**
     * 描述 : 标题  空值 : True  默认 :
     * @type {string}
     * @memberof MetIntegralRule
     */
    name?: string | null;
    /**
     * 描述 : 编码  空值 : True  默认 :
     * @type {string}
     * @memberof MetIntegralRule
     */
    code?: string | null;
    /**
     * 积分
     * @type {number}
     * @memberof MetIntegralRule
     */
    integral?: number;
    /**
     * 描述 : 一段时间  空值 : True  默认 :
     * @type {string}
     * @memberof MetIntegralRule
     */
    period?: string | null;
    /**
     * 一段时间次数
     * @type {number}
     * @memberof MetIntegralRule
     */
    limit?: number;
    /**
     * 积分开始时间
     * @type {Date}
     * @memberof MetIntegralRule
     */
    startTime?: Date;
    /**
     * 积分结束时间
     * @type {Date}
     * @memberof MetIntegralRule
     */
    endTime?: Date;
    /**
     * 备注
     * @type {string}
     * @memberof MetIntegralRule
     */
    remark?: string | null;
}
