/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetGroup } from './met-group';
import { StatusEnum } from './status-enum';
/**
 * 分组管理
 * @export
 * @interface MetGroup
 */
export interface MetGroup {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetGroup
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetGroup
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetGroup
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetGroup
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetGroup
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetGroup
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetGroup
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetGroup
     */
    isDelete?: boolean;
    /**
     * 父Id
     * @type {number}
     * @memberof MetGroup
     */
    pid?: number;
    /**
     * 名称
     * @type {string}
     * @memberof MetGroup
     */
    name: string;
    /**
     * 编码
     * @type {string}
     * @memberof MetGroup
     */
    code?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof MetGroup
     */
    orderNo?: number;
    /**
     * 
     * @type {StatusEnum}
     * @memberof MetGroup
     */
    status?: StatusEnum;
    /**
     * 备注
     * @type {string}
     * @memberof MetGroup
     */
    remark?: string | null;
    /**
     * 组别子项
     * @type {Array<MetGroup>}
     * @memberof MetGroup
     */
    children?: Array<MetGroup> | null;
}
