/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentTypeEnum } from './content-type-enum';
import { MetGroup } from './met-group';
import { MetProduct } from './met-product';
/**
 * 文章详情
 * @export
 * @interface MetArticle
 */
export interface MetArticle {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetArticle
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetArticle
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetArticle
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetArticle
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetArticle
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetArticle
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetArticle
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetArticle
     */
    isDelete?: boolean;
    /**
     * 描述 : 标题  空值 : True  默认 :
     * @type {string}
     * @memberof MetArticle
     */
    name?: string | null;
    /**
     * 描述 : 简介  空值 : True  默认 :
     * @type {string}
     * @memberof MetArticle
     */
    introduction?: string | null;
    /**
     * 描述 : 主形象  空值 : True  默认 :
     * @type {string}
     * @memberof MetArticle
     */
    mainImgUrl?: string | null;
    /**
     * 描述 : 内容  空值 : True  默认 :
     * @type {string}
     * @memberof MetArticle
     */
    contentText?: string | null;
    /**
     * 
     * @type {ContentTypeEnum}
     * @memberof MetArticle
     */
    type?: ContentTypeEnum;
    /**
     * 品牌ID
     * @type {number}
     * @memberof MetArticle
     */
    productId?: number | null;
    /**
     * 
     * @type {MetProduct}
     * @memberof MetArticle
     */
    product?: MetProduct;
    /**
     * 排序
     * @type {number}
     * @memberof MetArticle
     */
    orderNo?: number;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {number}
     * @memberof MetArticle
     */
    visits?: number;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetArticle
     */
    isSuggest?: boolean;
    /**
     * 描述 :    空值 : True  默认 :
     * @type {boolean}
     * @memberof MetArticle
     */
    isOnline?: boolean;
    /**
     * 文章分组
     * @type {number}
     * @memberof MetArticle
     */
    articleGroupId?: number;
    /**
     * 
     * @type {MetGroup}
     * @memberof MetArticle
     */
    meetGroupInfo?: MetGroup;
}
