/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SysUser } from './sys-user';
/**
 * 积分榜
 * @export
 * @interface MetStaffIntegralRunkOutput
 */
export interface MetStaffIntegralRunkOutput {
    /**
     * 用户ID
     * @type {number}
     * @memberof MetStaffIntegralRunkOutput
     */
    userId?: number;
    /**
     * 邀请积分
     * @type {number}
     * @memberof MetStaffIntegralRunkOutput
     */
    inviteIntegral?: number;
    /**
     * 
     * @type {SysUser}
     * @memberof MetStaffIntegralRunkOutput
     */
    staff?: SysUser;
}
