/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 礼品详情
 * @export
 * @interface MetGift
 */
export interface MetGift {
    /**
     * 雪花Id
     * @type {number}
     * @memberof MetGift
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof MetGift
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof MetGift
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof MetGift
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof MetGift
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof MetGift
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof MetGift
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof MetGift
     */
    isDelete?: boolean;
    /**
     * 名称
     * @type {string}
     * @memberof MetGift
     */
    name: string;
    /**
     * 礼品图片
     * @type {string}
     * @memberof MetGift
     */
    icon: string;
    /**
     * 描述 : 编码  空值 : True  默认 :
     * @type {string}
     * @memberof MetGift
     */
    code?: string | null;
    /**
     * 积分价值
     * @type {number}
     * @memberof MetGift
     */
    integral: number;
    /**
     * 排序
     * @type {number}
     * @memberof MetGift
     */
    orderNo?: number;
    /**
     * 备注
     * @type {string}
     * @memberof MetGift
     */
    remark?: string | null;
}
