/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetStaffIntegralRunkOutput } from './met-staff-integral-runk-output';
import { SysUser } from './sys-user';
/**
 * 
 * @export
 * @interface RankOutput
 */
export interface RankOutput {
    /**
     * 
     * @type {Array<MetStaffIntegralRunkOutput>}
     * @memberof RankOutput
     */
    list?: Array<MetStaffIntegralRunkOutput> | null;
    /**
     * 
     * @type {MetStaffIntegralRunkOutput}
     * @memberof RankOutput
     */
    useIntegral?: MetStaffIntegralRunkOutput;
    /**
     * 
     * @type {SysUser}
     * @memberof RankOutput
     */
    useInfo?: SysUser;
    /**
     * 
     * @type {number}
     * @memberof RankOutput
     */
    useIndex?: number;
}
