/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlatformTypeEnum } from './platform-type-enum';
import { UserIdentityEnum } from './user-identity-enum';
/**
 * 系统微信用户表
 * @export
 * @interface SysWechatUser
 */
export interface SysWechatUser {
    /**
     * 雪花Id
     * @type {number}
     * @memberof SysWechatUser
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysWechatUser
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysWechatUser
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysWechatUser
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof SysWechatUser
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysWechatUser
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof SysWechatUser
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof SysWechatUser
     */
    isDelete?: boolean;
    /**
     * 用户ID
     * @type {number}
     * @memberof SysWechatUser
     */
    userId?: number;
    /**
     * 
     * @type {UserIdentityEnum}
     * @memberof SysWechatUser
     */
    userIdentity?: UserIdentityEnum;
    /**
     * 
     * @type {PlatformTypeEnum}
     * @memberof SysWechatUser
     */
    platformType?: PlatformTypeEnum;
    /**
     * OpenId
     * @type {string}
     * @memberof SysWechatUser
     */
    openId: string;
    /**
     * 会话密钥
     * @type {string}
     * @memberof SysWechatUser
     */
    sessionKey?: string | null;
    /**
     * UnionId
     * @type {string}
     * @memberof SysWechatUser
     */
    unionId?: string | null;
    /**
     * 昵称
     * @type {string}
     * @memberof SysWechatUser
     */
    nickName?: string | null;
    /**
     * 头像
     * @type {string}
     * @memberof SysWechatUser
     */
    avatar?: string | null;
    /**
     * 手机号码
     * @type {string}
     * @memberof SysWechatUser
     */
    mobile?: string | null;
    /**
     * 性别
     * @type {number}
     * @memberof SysWechatUser
     */
    sex?: number | null;
    /**
     * 语言
     * @type {string}
     * @memberof SysWechatUser
     */
    language?: string | null;
    /**
     * 城市
     * @type {string}
     * @memberof SysWechatUser
     */
    city?: string | null;
    /**
     * 省
     * @type {string}
     * @memberof SysWechatUser
     */
    province?: string | null;
    /**
     * 国家
     * @type {string}
     * @memberof SysWechatUser
     */
    country?: string | null;
}
