/* tslint:disable */
/* eslint-disable */
/**
 * 恒瑞代谢公众号
 * 恒瑞代谢相关公众号接口
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 用户身份枚举<br />&nbsp;未知 Unknown = 0<br />&nbsp;员工 Staff = 1<br />&nbsp;医生 Doctor = 2<br />
 * @export
 * @enum {string}
 */
export enum UserIdentityEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

